Improve automatic `var` injection
tailwindlabs/tailwindcss pull request #12236
Opened 2023-10-18 11:43 UTC by RobinMalfait

This PR improves the automatic `var` injection behaviour.

When using arbitrary properties such as:
```html
<div class="[timeline-scope:--foo]"></div>
```

Then the compiled CSS will be:
```css
.\[timeline-scope\:--foo\]{
  timeline-scope: var(--foo)
}
```

However, the `timeline-scope` property accepts a `<dashed-ident>` data type, which means that the value should stay as `--foo`, and not `var(--foo)`.

This PR has an exceptions list for these properties, and won't wrap the variable with `var()` for properties that accept `<dashed-ident>`.

More info:
- https://drafts.csswg.org/scroll-animations/#propdef-timeline-scope
- https://developer.mozilla.org/en-US/docs/Web/CSS/timeline-scope#dashed-ident

Fixes: #12205

2023-10-18 11:48 UTC, RobinMalfait commented
@thecrypticace what do you think about this solution?

This only solves it for arbitrary properties, and not when you use it inside of a plugin. Alternatively we can write a Lightning CSS plugin that strips the `var()` for properties that accept `<dashed-ident>`. That way _all_ properties regardless where they are coming from will be fixed.

But, not generating them in the first place seems better I think.

Also, it looks like you can't use `var(--foo)` at all, because if you then define `--foo` as `--tl` Chrome devtools don't seem to resolve these correctly, so a Lightning CSS plugin seems doable. However, if it _is_ allowed, then this solution won't work.

Example of what I mean with variables: https://play.tailwindcss.com/Y5fbjtUBHa

2023-10-18 11:59 UTC, thecrypticace commented on src/util/dataTypes.js
> +  'view-timeline',
`font-palette` also needs to be in this list

2023-10-18 12:01 UTC, thecrypticace commented on src/util/dataTypes.js
> +    (context ? !AUTO_VAR_INJECTION_EXCEPTIONS.has(context.property) : true) &&
can we split this into it's own var or something. This is just kinda hard to scan.

2023-10-18 12:02 UTC, thecrypticace commented on src/util/dataTypes.js
> +    (context ? !AUTO_VAR_INJECTION_EXCEPTIONS.has(context.property) : true) &&
Maybe:

```js
let isVarException = context && AUTO_VAR_INJECTION_EXCEPTIONS.has(context.property)

if (value.startsWith('--') && !isVarException) { /* … */ }
```

2023-10-18 12:07 UTC, thecrypticace requested changes
Looks good other than needing to add the `font-palette` property and cleanup that one if statement.

2023-10-18 14:32 UTC, thecrypticace commented
LGTM. The `rollup-sass` integration test has become super flaky with timing btw. Need to figure out how to fix that so you can ignore it.

2023-10-18 14:32 UTC, thecrypticace approved these changes

2023-10-24 12:08 UTC, merged

2024-03-11 23:48 UTC, mrcsmcln commented
+1 as I'm currently experiencing this issue while transitioning @property values. Currently using an underscore (e.g., `transition-[_--foo]`.