Process Tailwind output with other Vite plugins
tailwindlabs/tailwindcss pull request #13218
Opened 2024-03-12 16:27 UTC by KrisBraun

Transform Tailwind-generated CSS with other Vite plugins. `vite:css`, in particular, does useful things like transforming `url()` paths and inlining images.

Several plugins are explicitly skipped because they were failing.`vite:css-post` translates CSS into a JS module for the dev server, but fails to reload the Tailwind CSS, perhaps because it's happening too late in the pipeline. 

This PR also removes the timeout used to detect the end of the initial scan. Now that full builds wait until the bundle stage, dev builds can simply run immediately. This might build Tailwind CSS twice, generating a FOUC (since the first build hasn't seen all candidates), but is much faster than waiting for the timeout. A [proposed Vite change](https://github.com/vitejs/vite/pull/16135) could address the FOUC and extra build.

2024-03-14 13:28 UTC, KrisBraun commented
@ArnaudBarre I'm interested in your review here. In particular, do you see any cases where this won't work with other plugins correctly?

2024-03-18 15:06 UTC, ArnaudBarre commented
Answered in Discord: this way of doing things doesn't make the CSS hash independent of the utils content. To workaround that I found that calling again the transform function of the `vite:css-post` plugin with the same id but the new content gives expected result, without the need for a fake id or placeholder. It will automatically apply all the transformation from Vite (but not from other plugins, which is fine IMO)

2024-03-22 14:26 UTC, KrisBraun commented
@ArnaudBarre The PR has been updated to apply the `renderChunk` technique.

2024-03-22 17:01 UTC, thecrypticace requested changes

2024-03-22 17:01 UTC, thecrypticace commented on playgrounds/vite/vite.config.js
The `package.json` in The Vite playground needs to be updated otherwise it doesn't work.

2024-03-22 17:05 UTC, thecrypticace commented
Some small changes but otherwise looks good and appears to work quite well. 💯

2024-03-22 17:24 UTC, KrisBraun commented on playgrounds/vite/vite.config.js
Unintentional change (part of testing Storybook). Backing it out.

2024-03-22 18:33 UTC, thecrypticace approved these changes

2024-03-22 18:57 UTC, merged