Migrate simple PostCSS setup
tailwindlabs/tailwindcss pull request #14612
Opened 2024-10-07 12:43 UTC by philipp-spiess

This PR attempts to detect simple postcss setups: These are setups that do not load dynamic modules and are based off the examples we are [recommending in our docs](https://tailwindcss.com/docs/installation/using-postcss). We detect wether a config is appropriate by having it use the object plugin config and by not requiring any other modules:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

When we find such a config file, we will go over it line-by-line and attempt to:

- Upgrade `tailwindcss:` to `'@tailwindcss/postcss':`
- Remove `autoprefixer` if used

We then attempt to install and remove the respective npm packages based on the package manger we detect.

And since we now have logic to upgrade packages, this also makes sure to install `tailwindcss@next` at the end of a sucessful migration.

2024-10-07 15:15 UTC, RobinMalfait reviewed
We have some failing tests 🤔

2024-10-07 15:15 UTC, RobinMalfait commented on packages/@tailwindcss-upgrade/src/utils/packages.ts
> +        }
Do we want bun support as well?

```suggestion
        if (packageJson.packageManager.includes('bun')) {
          return 'bun'
        }
        if (packageJson.packageManager.includes('yarn')) {
          return 'yarn'
        }
```

2024-10-07 15:15 UTC, RobinMalfait commented on packages/@tailwindcss-upgrade/src/utils/packages.ts
> +    // 2. Check for common lockfiles
We can probably do this in a cleaner way. But bun is switching from `bun.lockb` (binary) to a `bun.lock` (text) file.
```suggestion
    // 2. Check for common lockfiles
    try {
      await fs.access(resolve(base, 'bun.lockb'))
      return 'bun'
    } catch {}
    try {
      await fs.access(resolve(base, 'bun.lock'))
      return 'bun'
    } catch {}
```

2024-10-08 11:45 UTC, philipp-spiess reviewed
Some comments from my call with @RobinMalfait that I will fix up 👍

2024-10-08 11:45 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +      newLines.push(line.replace('tailwindcss:', `'@tailwindcss/postcss':`))
If the previous line here is the nesting plugin, we can remove it as well: 

- https://tailwindcss.com/docs/using-with-preprocessors#nesting

2024-10-08 11:45 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +    // TODO: We can look for an eventual config inside package.json
https://sourcegraph.com/search?q=context:global+file:package.json+%27%22postcss%22:+%7B%27+tailwindcss&patternType=keyword&sm=0 let's support it

2024-10-08 11:45 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/utils/packages.ts
> +  })
If this fails, we should print a message that explains what we tried to do

2024-10-08 15:29 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +    content.includes('tailwindcss:') && !(content.includes('require') || content.includes('import'))
what about postcss-import? heh

2024-10-08 15:33 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +    content.includes('tailwindcss:') && !(content.includes('require') || content.includes('import'))
```suggestion
    content.includes('tailwindcss:') && !(content.includes('require') || content.includes('import '))
```

2024-10-08 15:33 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +    }
Should check for `{}` before deleting a line

2024-10-08 15:34 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +      newLines.push(line.replace('tailwindcss:', `'@tailwindcss/postcss':`))
also remove `postcss-import` if nothing else is between it and `tailwindcss`

2024-10-09 18:35 UTC, thecrypticace requested changes, later dismissed
Just a couple things but otherwise looks good!

2024-10-09 18:35 UTC, thecrypticace commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +  }
We should merge these two `remove` calls into one command given that npm add/remove can sometimes take a decent chunk of time.

As far as I know every package manager supports removing more than one package

2024-10-09 18:35 UTC, thecrypticace commented on packages/@tailwindcss-upgrade/src/migrate-postcss.ts
> +  'postcss.config.cts',
As far as I know `.postcssrc`, `.postcssrc.json`, and `postcss.config.json` can also exist and use JSON. I think this is more common when using Next. We'll need to double check the logic in `postcss-load-config` to verify.

We could probably reuse some of the package.json config stuff for these files.

2024-10-10 13:01 UTC, thecrypticace approved these changes

2024-10-10 13:09 UTC, merged