Upgrade: Error when project is already using Tailwind CSS v4
tailwindlabs/tailwindcss pull request #15015
Opened 2024-11-15 17:05 UTC by philipp-spiess

In some local testing we ran the `@tailwindcss/upgrade` command twice in a row. It would be great to get some feedback that this is not working, so this PR now checks if it can resolve the installed version of `tailwindcss` and if it can, it requires it to be < 4 (you can bypass this check with `--force`).

2024-11-15 18:20 UTC, RobinMalfait requested changes

2024-11-15 18:20 UTC, RobinMalfait commented on integrations/upgrade/index.test.ts
> +      .replace(/\\/g, '/') // Make Windows paths look like Unix paths
I don't think this is necessary because we use the `toMatch` with a regex.

```suggestion
```

2024-11-18 09:31 UTC, philipp-spiess commented on packages/@tailwindcss-upgrade/src/utils/package-version.ts
> +    const { version } = JSON.parse(await fs.readFile(packageJson, 'utf8'))
lol I have forgotten everything when i did this pr huh

2024-11-18 14:23 UTC, RobinMalfait requested changes
Also needs a changelog entry

2024-11-18 14:23 UTC, RobinMalfait commented on integrations/upgrade/index.test.ts
> +test.only(
```suggestion
test(
```

2024-11-18 14:23 UTC, RobinMalfait commented on packages/@tailwindcss-upgrade/src/index.ts
> +    console.error({ tailwindVersion })
```suggestion
```

2024-11-18 16:46 UTC, RobinMalfait commented on CHANGELOG.md
> +- Allow `addUtilities()` and `addComponents()` to work with child combinators and other complex selectors ([#15029](https://github.com/tailwindlabs/tailwindcss/pull/15029))
```suggestion
```

2024-11-19 14:51 UTC, RobinMalfait approved these changes

2024-11-19 14:53 UTC, merged