Support complex `addUtility()` configs
tailwindlabs/tailwindcss pull request #15029
Opened 2024-11-18 12:51 UTC by philipp-spiess

2024-11-18 15:03 UTC, RobinMalfait approved these changes

2024-11-18 15:08 UTC, thecrypticace approved these changes

2024-11-18 18:03 UTC, thecrypticace commented on packages/tailwindcss/src/compat/selector-parser.test.ts
> +    `)
```suggestion
    expect(parse(':nth-child(n+1)')).toEqual([
      {
        kind: 'function',
        value: ':nth-child',
        nodes: [
          {
            kind: 'value',
            value: 'n+1',
          },
        ],
      },
    ])
```

2024-11-18 18:07 UTC, thecrypticace requested changes
a small thing in the tests but otherwise seems good

2024-11-19 09:14 UTC, philipp-spiess commented on packages/tailwindcss/src/compat/selector-parser.ts
> +      }
Ah, thanks, missed the plus sign in a list 😬  Fixed!

2024-11-19 14:34 UTC, thecrypticace approved these changes

2024-11-19 14:52 UTC, merged

2024-11-22 12:28 UTC, davidmatter commented
@philipp-spiess Am I right to assume that in v4, we need to migrate from

```js
{
  '@media (min-width: 768px)': {
    .article-display-m {
      font-size: 60px;
    }
  }
}
```
 to:
 ```js
{
  .article-display-m {
    '@media (min-width: 768px)': {
      font-size: 60px;
    }
  }
}
```

2024-11-22 12:35 UTC, philipp-spiess commented
@davidmatter Huh this is... interesting! Yes if you can migrate to that that would be easiest. Is this a plugin doing or how did you discover this?

2024-11-22 12:48 UTC, davidmatter commented
We're quite a large company with a large CSS-based design system with hundreds of (for example) typography definitions. Now, to get proper intellisense in our code editors and to integrate better with our tailwind projects, we've come up with a custom plugin that parses CSS and adds the definitions to tailwind using `addUtilities`.

e.g.
```
  const root = parse(css)
  const jss = objectify(root)
  addUtilities(jss)
```

It works quite well actually in v3 :) In a perfect world, these definitions would of course be extracted to their own components to support the official tailwind way of doing things etc. but that would be A LOT of work.

2024-11-22 12:55 UTC, davidmatter commented
For parsing and `objectify`, we use https://github.com/postcss/postcss-js

2024-11-22 13:43 UTC, philipp-spiess commented
I see, so you're not expecting this to generate the right CSS anyways and only use this to extend the type hints for intellisense? I think it should be possible to write a quick function that inverts the object properties in this case?

2024-11-25 06:55 UTC, davidmatter commented
@philipp-spiess Thanks for taking the time. Well, we actually use it to generate prunable CSS. TBH I think it's the best pattern to work with legacy CSS code because of 1) Intellisense and 2) Resulting CSS can be pruned by tailwind and runs through the official plugin system.

Inverting the objects is alright for us. I suspect that we're not the only ones using this pattern, though. Might be advisable to mark this as a breaking change to save everyone's time :)

2024-11-25 06:58 UTC, davidmatter commented
BTW: Good to see an Austrian engineer being part of tailwind! Keep it up