Support array of config objects + extending core plugins config
tailwindlabs/tailwindcss pull request #2474
Opened 2020-09-30 17:00 UTC by adamwathan

This PR adds support for defining your Tailwind config as an _array_, to make it possible to ignore Tailwind's default config file.

```js
// tailwind.config.js
module.exports = [
  { theme: { ... } },
  { theme: { ... } },
]
```

Whenever an array is provided instead of an object, Tailwind will not include the default config when resolving the config, which makes it possible for you to provide your own default config that you reuse from project to project, completely ignoring Tailwind's defaults.

Now the object syntax for the config is equivalent to this:

```js
// tailwind.config.js
const defaultConfig = require('tailwindcss/defaultConfig')

module.exports = [
  defaultConfig,
  {
    theme: { ... },
    // ...
  }
]
```

This PR also adds better support for merging the `corePlugins` key, so now your custom default config can specify the core plugins you want to enable while still being able to extend it in a project specific config:

```js
// tailwind.config.
const sharedConfig = {
  // ...
  corePlugins: ['backgroundColor', 'float', 'opacity', 'padding']
}

module.exports = [
  sharedConfig,
  {
    // ...
    corePlugins: {
      float: false,
    }
  }
]
```

If you'd like to add core plugins to your base config, you can use a function syntax that receives the so-far-resolved `corePlugins` array as a destructurable argument:

```js
// tailwind.config.
const sharedConfig = {
  // ...
  corePlugins: ['backgroundColor', 'float', 'opacity', 'padding']
}

module.exports = [
  sharedConfig,
  {
    // ...
    corePlugins: ({ corePlugins }) => {
      return [...corePlugins, 'margin']
    }
  }
]
```

We may add helpers like `after` and `before` in the future, to mimic the API that is available for variants.

This PR in general is in service of introducing a new "lite" config mode for Tailwind, for folks who want a more minimal starting point.

2020-10-03 21:54 UTC, adamwathan commented
To do:  consider changing to a preset key instead of an array config, and make sure it works recursively.

2020-10-04 19:17 UTC, adamwathan commented
Updated to drop the top level array format and instead use a `presets` key.

2020-10-04 20:06 UTC, MichaelDeBoey requested changes

2020-10-04 20:06 UTC, MichaelDeBoey commented on src/corePlugins.js
> +    return corePluginList[pluginName]()
```suggestion
  return configurePlugins(corePluginConfig, Object.values(corePluginList)).map(plugin => {
    return plugin()
```

2020-10-04 20:39 UTC, leodr commented
Since `tailwind.config.js` is already a JavaScript file, can't you just use the object spread syntax to extend other themes? And disable the default theme by supplying an empty object to the theme property?

2020-10-04 20:45 UTC, adamwathan commented
Nope, the resolution logic is quite complex because of things like function values and the “extend” theme key. Check out the tests for resolveConfig 😳

2020-10-07 21:12 UTC, mnaderian commented
I'm waiting for the day when Bootstrap is completely beaten. Then we can rule the world again!! Tailwind CSS should really rule the web cause it's really better than others and has better taste.

As all fathers say: Be patient son!

2020-10-08 15:21 UTC, merged

2020-10-13 08:39 UTC, soullivaneuh commented
@adamwathan I am not really sure of the usage target of this feature.

I have a `design` project containing a common tailwind configuration file for our company: https://gitlab.com/nexylan/design/-/blob/6d853ad113e064d4d34e8240dacd47a462293edd/tailwind.config.js

As you can see on this version, I require some part of the default theme then merge them using the spread operators.

Will your feature help me on that case or should I keep my configuration like this?

The goal of this config is also to be re-used on other project containing a tailwind configuration.

In a more general way, will some documentation be added about this feature?

Regards

2020-10-13 18:58 UTC, adamwathan commented
You can use this feature to specify your custom config file as the base for any projects you work on like this:

```js
// tailwind.config.js
module.exports = {
  presets: [require('./custom-base-config.js')],
  // ...
}
```

Can you explain more clearly what your question is? How were you extending your base config in your projects up until now?

2020-10-19 08:29 UTC, soullivaneuh commented
@adamwathan The main goal is to maintain one common Tailwind configuration under our design project and maybe add some specific override on front projects.

2020-10-19 14:21 UTC, soullivaneuh commented
By the way, I maybe didn't understand the goal of this feature, but I tried this:


```typescript
presets: [
  require('tailwindcss/defaultConfig'),
  require('nexylan-design/tailwind.config.js'),
],
```

And the design is completely broken. However, if I remove the custom one, everything works well but without my theme (of course).