feat: transform `hsl` to `hsla`
tailwindlabs/tailwindcss pull request #3850
Opened 2021-03-26 10:28 UTC by fedeci

This fixes #3834 
We preserve the `hsl` colors by converting it to `hsla` instead of `rgba`.
e.g.
```diff
hsl(0, 0%, 0%)
- rgba(0, 0, 0, var(--opacity))
+ hsla(0, 0, 0, var(--opacity))
```

2021-03-26 10:31 UTC, fedeci commented on src/util/withAlphaVariable.js
> +    const [i, j, k, a] = isHSL ? toHsla(color) : toRgba(color)
We use generic component names

2021-03-26 16:55 UTC, adamwathan commented
Looking good, I noticed you still have this set as a draft so just let me know when you'd like me to look into merging 👍🏻 Thanks!

2021-03-26 17:14 UTC, fedeci commented
Yess, I saw that `toRgba` is used in other places, so I would take a look at those too.

2021-03-27 08:12 UTC, fedeci commented
@adamwathan it should be ready to be merged if it passes the tests

2021-03-27 14:48 UTC, andronocean requested changes
This isn't quite right. The saturation and lightness parameters in `hsl()` or `hsla()` colors are percentages, not numbers, so they need to be followed by the `%` symbol. The tests pass, but the tests are expecting the wrong values. ([See MDN description](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsl_colors))

2021-03-27 14:48 UTC, andronocean commented on __tests__/plugins/gradientColorStops.test.js
> +        color: hsla(10, 50, 50, var(--tw-text-opacity));
```css
color: hsla(10, 50%, 50%, var(--tw-text-opacity));
```

2021-03-27 14:48 UTC, andronocean commented on __tests__/plugins/gradientColorStops.test.js
> +        --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, hsla(10, 50, 50, 0));
```css
--tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, hsla(10, 50%, 50%, 0));
```

2021-03-27 14:48 UTC, andronocean commented on __tests__/plugins/gradientColorStops.test.js
> +        var(--tw-gradient-to, hsla(10, 50, 50, 0));
```css
var(--tw-gradient-to, hsla(10, 50%, 50%, 0));
```

2021-03-27 14:48 UTC, andronocean commented on __tests__/plugins/ringWidth.test.js
> +          '--tw-ring-color': 'hsla(10, 50, 50, 0.5)',
```
'--tw-ring-color': 'hsla(10, 50%, 50%, 0.5)',
```

2021-03-27 14:48 UTC, andronocean commented on __tests__/withAlphaVariable.test.js
> +    'background-color': 'hsla(50, 50, 50, var(--tw-bg-opacity))',
```
'background-color': 'hsla(50, 50%, 50%, var(--tw-bg-opacity))',
```

2021-03-30 00:35 UTC, andronocean approved these changes
Looks good to me 😎 (Thank you @fedeci !)

2021-04-14 13:28 UTC, andronocean commented
Hey @adamwathan, any way to get this merged this week or next? It'd be really helpful 🙏

2021-04-30 13:09 UTC, merged