Add `background-origin` utilities
tailwindlabs/tailwindcss pull request #4117
Opened 2021-04-19 18:15 UTC by davidluhr

This PR adds support for the [`background-origin`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin) property.

An example use case is a button with a gradient background and transparent border. This typically results in unexpected border colors appearing, but can be fixed with `background-origin: border-box;` in CSS (or `bg-origin-border` in Tailwind CSS with this PR).

Here's the API:

| Class | CSS |
| --- | --- |
| `bg-origin-border` |  `background-origin: border-box` |
| `bg-origin-padding` |  `background-origin: padding-box` |
| `bg-origin-content` |  `background-origin: content-box` |

Only `responsive` variants are enabled by default, but can be configured under the `backgroundOrigin` key in your `tailwind.config.js` file.

2021-04-19 19:37 UTC, bagsa requested changes

2021-04-19 19:37 UTC, bagsa commented on __tests__/fixtures/tailwind-output-flagged.css
> +/*! tailwindcss v2.1.1 | MIT License | https://tailwindcss.com */
[]()

2021-04-19 19:37 UTC, bagsa commented on __tests__/fixtures/tailwind-output-important.css
> +
**
```suggestion
**[]()**
```
**

2021-04-19 19:37 UTC, bagsa commented on __tests__/fixtures/tailwind-output-flagged.css
> +/*! tailwindcss v2.1.1 | MIT License | https://tailwindcss.com */
****

2021-04-20 16:43 UTC, adamwathan commented
Well done Mr. Luhr, well done.

2021-04-20 16:43 UTC, merged