Adding touch-action utility
tailwindlabs/tailwindcss pull request #4727
Opened 2021-06-20 23:17 UTC by MatteoGauthier

Hey guys, i added the `touch-action` css property to tailwind :D

2021-06-21 13:00 UTC, adamwathan requested changes
Hey thanks for this one, had this on my list to add soon so cool to have it come in as a PR! Left a few bits of feedback for things that need to change but generally looks good, thanks again.

2021-06-21 14:43 UTC, MatteoGauthier commented on src/plugins/index.js
> +export { default as touchAction } from './touchAction'
Hey, thank you for your review. I will change that 👌

2021-06-21 14:46 UTC, MatteoGauthier commented on tests/jit/basic-usage.test.html
>    </body>
Yes of course (i forgot to disable headwind vscode extension)

2021-06-21 15:11 UTC, MatteoGauthier commented on stubs/defaultConfig.stub.js
> +    },
hey, i removed lines you've noticed :D

2021-06-21 15:12 UTC, MatteoGauthier commented
@adamwathan I tried to correct issues you noticed 📍

2021-06-22 13:53 UTC, MatteoGauthier commented
I don't know why the `test` fail..

2021-06-22 15:52 UTC, sachinraja commented
I think the problem is that you didn't regenerate the fixtures after moving the import position. Looks like you'll also have to change the class's position in `tests/jit/basic-usage.test.css`. Tests pass for me after addressing both of these issues.

So you need to:
1. `npm run rebuild-fixtures`
2. move the `touch-manipulation` class to right after `cursor-pointer` in `tests/jit/basic-usage.test.css`.

2021-06-22 17:03 UTC, MatteoGauthier commented
I don't know why the tests still failing..

2021-09-26 13:40 UTC, adamwathan commented
Hey! We refactored the living hell out of the codebase since the time you opened this, so I just opened a new PR and included you as a co-author just to get this merged in quickly 👍🏻 

https://github.com/tailwindlabs/tailwindcss/pull/5603

Thanks a ton man!

2021-09-26 13:40 UTC, closed without merging

2021-09-26 13:48 UTC, MatteoGauthier commented
> Hey! We refactored the living hell out of the codebase since the time you opened this, so I just opened a new PR and included you as a co-author just to get this merged in quickly 👍🏻
> 
> #5603
> 
> Thanks a ton man!

Thanks Adam ! Have a good day :D