Improve return value of `resolveConfig`, unwrap `ResolvableTo`
tailwindlabs/tailwindcss pull request #9972
Opened 2022-11-30 12:44 UTC by RobinMalfait

This PR improves the return type fo the `resolveConfig` a little bit.

In the config, a lot of values can be written in various forms (and most of it is optional). We also
allow for dynamic "runtime" presets, so generating the perfect TypeScript types are almost
impossible.

However, some of the parts in the config accept a function that resolves to type `T`, this
improvement gets rid of the callback function and results in `T` directly (because calling
`resolveConfig` should resolve this).

Fixes: #9929

2022-11-30 12:58 UTC, thecrypticace commented on resolveConfig.d.ts
> +  theme: UnwrapResolvables<T['theme']>
You're gonna want to apply the same unwrapping to all the keys inside `theme.extend`

2022-11-30 13:00 UTC, thecrypticace commented on resolveConfig.d.ts
> +  theme: UnwrapResolvables<T['theme']>
Actually, let me re-word this. You need to unwrap all the keys inside theme.extend and then spread them into the top level object. Is that even possible??

2022-11-30 13:01 UTC, thecrypticace requested changes
General approach looks good sans the change for handling `theme.extend` unwrapping and merging.

2022-11-30 13:08 UTC, thecrypticace commented on resolveConfig.d.ts
> +  theme: UnwrapResolvables<T['theme']>
Scratch this. It'll require some ridiculousness with conditional types and what not. Nevermind.

2022-11-30 13:08 UTC, thecrypticace approved these changes

2022-11-30 13:26 UTC, merged

2023-07-20 19:25 UTC, justinh-kairos commented
I'm still seeing this with tailwind 3.3.2:
```
Property 'colors' does not exist on type 'UnwrapResolvables<{ container: { center: true; padding: string; screens: { "2xl": string; }; }; extend: { fontFamily: { sans: [string, ...string[]]; display: [string, ...string[]]; }; colors: { input: string; ring: { DEFAULT: string; offset: string; }; ... 10 more ...; card: { ...; }; }; borderRadius: { ...; }; keyf...'.ts(2339)
```

2024-01-19 08:41 UTC, stefusilviu commented
I confirm the same on 3.4.1

<img width="468" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4706535/66b6faa9-8c83-4263-9ac3-81eea0e2d353">

2024-02-09 03:01 UTC, theocerutti commented
No it still doesn't work:

```
const config = resolveConfig(tailwindConfig);

const mycolor = config.theme.colors.neutral['750']; // Element implicitly has an 'any' type because expression of type '750' can't be used to index type
```